INSERT INTO products (id, name, brand, category, subtype, price, description, "isActive", "createdAt", "updatedAt") VALUES
  (gen_random_uuid()::text, 'Ramo de rosas rojas', 'Flores de Miraflores', 'FLORES', 'Rosas', 89.90, 'Docena de rosas rojas frescas con follaje', true, now(), now()),
  (gen_random_uuid()::text, 'Arreglo de girasoles', 'Floristería San Isidro', 'FLORES', 'Girasoles', 75.00, 'Arreglo alegre de girasoles en base de cerámica', true, now(), now()),
  (gen_random_uuid()::text, 'Caja de flores secas', 'Pétalo Lima', 'FLORES', 'Flores secas', 120.00, 'Flores preservadas en caja decorativa, duran meses', true, now(), now()),
  (gen_random_uuid()::text, 'Vino tinto reserva', 'Bodega Tacama', 'VINOS', 'Vino tinto', 65.00, 'Reserva especial, botella de 750ml', true, now(), now()),
  (gen_random_uuid()::text, 'Champagne brut', 'Vinoteca Barranco', 'VINOS', 'Espumante', 180.00, 'Espumante importado para celebrar', true, now(), now()),
  (gen_random_uuid()::text, 'Pack de 2 vinos + copas', 'Enoteca Surco', 'VINOS', 'Pack de vinos', 210.00, 'Dos botellas seleccionadas con par de copas de regalo', true, now(), now()),
  (gen_random_uuid()::text, 'Torta de chocolate', 'Pastelería San Antonio', 'TORTAS', 'Chocolate', 95.00, 'Torta húmeda de chocolate, 8 porciones', true, now(), now()),
  (gen_random_uuid()::text, 'Torta de tres leches', 'Dulce Tentación', 'TORTAS', 'Tres leches', 85.00, 'Clásica tres leches con canela', true, now(), now()),
  (gen_random_uuid()::text, 'Cupcakes surtidos (12 unidades)', 'Sweet Lima', 'TORTAS', 'Cupcakes', 70.00, 'Caja de 12 cupcakes de sabores variados', true, now(), now()),
  (gen_random_uuid()::text, 'Caja de bombones premium', 'Chocolatería La Ibérica', 'CHOCOLATES', 'Bombones', 55.00, 'Surtido de bombones rellenos', true, now(), now()),
  (gen_random_uuid()::text, 'Chocolate artesanal 70% cacao', 'Cacao Perú', 'CHOCOLATES', 'Chocolate artesanal', 40.00, 'Tableta artesanal de cacao peruano', true, now(), now()),
  (gen_random_uuid()::text, 'Set de trufas', 'Chocolatte Miraflores', 'CHOCOLATES', 'Trufas', 68.00, 'Trufas artesanales de chocolate belga', true, now(), now()),
  (gen_random_uuid()::text, 'Vale de spa día completo', 'Spa Larcomar', 'SPA', 'Día completo', 250.00, 'Acceso a sauna, jacuzzi y un masaje de 60 minutos', true, now(), now()),
  (gen_random_uuid()::text, 'Sesión de masajes relajantes', 'Zen Spa San Isidro', 'SPA', 'Masajes', 150.00, 'Masaje relajante de cuerpo completo, 90 minutos', true, now(), now()),
  (gen_random_uuid()::text, 'Pack facial + manicure', 'Bella Lima Spa', 'SPA', 'Facial y manicure', 180.00, 'Limpieza facial profunda y manicure spa', true, now(), now()),
  (gen_random_uuid()::text, 'Caja "Para Mamá"', 'Presente Curado', 'CAJAS_CURADAS', 'Para mamá', 140.00, 'Flores, chocolates y una tarjeta personalizada', true, now(), now()),
  (gen_random_uuid()::text, 'Caja desayuno sorpresa', 'Brunch Box Perú', 'CAJAS_CURADAS', 'Desayuno', 95.00, 'Pan artesanal, mermeladas, jugo y fruta', true, now(), now()),
  (gen_random_uuid()::text, 'Caja relax', 'Calma Box', 'CAJAS_CURADAS', 'Relax', 110.00, 'Vela aromática, té premium y chocolates', true, now(), now());
